### ISSUE TITLE
it is great,where is the model?

### ISSUE THREAD

**Issue by sunjunlishi** [dafanghe/DeepSceneTextReader#1]

**Comment by dafanghe** [comment]
I will upload the model and let u know when I finish.

**Comment by sunjunlishi** [comment]
we all thank you.
Your method can carry out the fine location of the license plate, correct the license plate and even divide the characters between the cells. The rough location of the license plate can be used in other ways

**Comment by dafanghe** [comment]
I uploaded the pretrained model. U can play with it.
