### ISSUE TITLE
Read and detect mode

### ISSUE THREAD

**Issue by EsiNaderi** [dafanghe/DeepSceneTextReader#3]
Hi,

I build the code and it is perfectly working in detect and recognize mode... I get strange error on read and detect mode ...

This is my command:
 ./bin/DetectText --detector_graph='model/FasterRCNN_detector_model.pb' --recognizer_graph='model/Recognizer_model_case_insen.pb' --dictionary_filename='model/charset_case_insen.txt' --image_filename='test_images/img_108.jpg' --mode='detect_and_read' --output_filename='test_images/output_image_2.jpg'

which gives me this errors:
r/scene_text_reader.cpp:15] model/charset_case_insen.txt not implemented yet
r/recognizer.h:49] Error dictionary opening file FasterRCNN

What is possibly wrong? Even I commented these lines in source and recompiled it and got another error somewhere else...

**Comment by EsiNaderi** [comment]
Solved it by changing from,

scene_text_reader::SceneTextReader reader(detector_graph_filename,
      recognizer_graph_filename, dictionary_filename);


to in main.cpp :
scene_text_reader::SceneTextReader reader(detector_graph_filename,
      recognizer_graph_filename, "FasterRCNN", dictionary_filename, "CTC");


Great work!

**Comment by dafanghe** [comment]
Thanks for finding this problem. I just realized that there is some problem with the order of passing argument in the initialization function.
