### ISSUE TITLE
 how to use python to  training a  crnn model

### ISSUE THREAD

**Issue by jesen8** [dafanghe/DeepSceneTextReader#6]
hello, this repository is very good! thanks you! but i want to train my dataset with Chinese char, so can you post your crnn train code?,thanks so much!

**Comment by dafanghe** [comment]
Hi sorry for late reply.
There are many CRNN implementation available right now.
Like this one:
https://github.com/Belval/CRNN

I will share mine later. But it is pretty similar to the repo above as they are all based on its original implementation.
https://github.com/bgshih/crnn

Thanks.

**Comment by jesen8** [comment]
so I'm looking forward to it! 
Thanks.

**Comment by jesen8** [comment]
I will study carefully for the two repo!
Thanks.
